Repository merwanehamadi/Auto-GPT, pull requests merged in 2023-05, with the labels that each got.

#13 basic-proxy-test
  .github/workflows/docker-release.yml
Labels: size/xs

#24 basic proxy
  autogpt/prompts/prompt.py
  tests/integration/agent_factory.py
Labels: size/s

#31 basic proxy
  .github/workflows/add-cassettes.yml
  .github/workflows/ci.yml
Labels: size/xs

#50 basic proxy
  .github/workflows/ci.yml
  autogpt/config/ai_config.py
  autogpt/llm/api_manager.py
  tests/integration/conftest.py
  tests/integration/goal_oriented/cassettes/test_write_file/test_write_file.yaml
  tests/integration/goal_oriented/test_write_file.py
  tests/test_api_manager.py
Labels: size/xl

#54 add thoughts type
  .github/workflows/add-cassettes.yml
  .github/workflows/ci.yml
  autogpt/llm/api_manager.py
  autogpt/llm/llm_utils.py
  tests/conftest.py
  tests/integration/challenges/information_retrieval/test_information_retrieval_challenge_a.py
  tests/integration/challenges/memory/test_memory_challenge_a.py
  tests/integration/challenges/memory/test_memory_challenge_b.py
  tests/integration/challenges/memory/test_memory_challenge_c.py
  tests/integration/conftest.py
  tests/integration/goal_oriented/test_browse_website.py
  tests/integration/goal_oriented/test_write_file.py
  tests/integration/test_commands.py
  tests/integration/test_llm_utils.py
  tests/integration/test_local_cache.py
  tests/integration/test_memory_management.py
  tests/integration/test_setup.py
  tests/test_api_manager.py
  tests/test_image_gen.py
  tests/utils.py
  tests/vcr/vcr_filter.py
Labels: size/xl

#55 basic proxy
  autogpt/prompts/prompt.py
  tests/integration/goal_oriented/test_write_file.py
Labels: size/s

#126 Feature/hackathon add basic challenge
  .github/workflows/ci.yml
  autogpt/commands/git_operations.py
  requirements.txt
  tests/integration/agent_factory.py
  tests/integration/challenges/pr_review/base.py
  tests/integration/challenges/pr_review/test_basic_pr_review.py
Labels: size/xl

#153 unused variable example
  tests/integration/challenges/pr_review/props/bad_variables.py
Labels: size/s
